#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : gpm
Version  : e82d1a653ca94aa4ed12441424da6ce780b1e530
Release  : 7
URL      : https://github.com/telmich/gpm/archive/e82d1a653ca94aa4ed12441424da6ce780b1e530.tar.gz
Source0  : https://github.com/telmich/gpm/archive/e82d1a653ca94aa4ed12441424da6ce780b1e530.tar.gz
Source1  : gpm.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gpm-autostart = %{version}-%{release}
Requires: gpm-bin = %{version}-%{release}
Requires: gpm-data = %{version}-%{release}
Requires: gpm-info = %{version}-%{release}
Requires: gpm-lib = %{version}-%{release}
Requires: gpm-license = %{version}-%{release}
Requires: gpm-man = %{version}-%{release}
Requires: gpm-services = %{version}-%{release}
BuildRequires : bison
BuildRequires : emacs
BuildRequires : gpm-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : texinfo
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Don-t-use-emacs-site-lisp-detection.patch

%description
/*
*
*
*******/
The gpm (general purpose mouse) daemon tries to be a useful mouse
server for applications running on the Linux console.  Its roots are
in the "selection" package, by Andrew Haylett, and the original code
comes from selection itself. This package is intended as a replacement
for "selection", to provide additional facilities.  From 0.18 onward
gpm supports xterm as well, so you can run mouse-sensitive
applications under X, and you can easily write curses applications
which support the mouse on both the Linux console and xterm. The xterm

%package autostart
Summary: autostart components for the gpm package.
Group: Default

%description autostart
autostart components for the gpm package.


%package bin
Summary: bin components for the gpm package.
Group: Binaries
Requires: gpm-data = %{version}-%{release}
Requires: gpm-license = %{version}-%{release}
Requires: gpm-services = %{version}-%{release}

%description bin
bin components for the gpm package.


%package data
Summary: data components for the gpm package.
Group: Data

%description data
data components for the gpm package.


%package dev
Summary: dev components for the gpm package.
Group: Development
Requires: gpm-lib = %{version}-%{release}
Requires: gpm-bin = %{version}-%{release}
Requires: gpm-data = %{version}-%{release}
Provides: gpm-devel = %{version}-%{release}
Requires: gpm = %{version}-%{release}

%description dev
dev components for the gpm package.


%package info
Summary: info components for the gpm package.
Group: Default

%description info
info components for the gpm package.


%package lib
Summary: lib components for the gpm package.
Group: Libraries
Requires: gpm-data = %{version}-%{release}
Requires: gpm-license = %{version}-%{release}

%description lib
lib components for the gpm package.


%package license
Summary: license components for the gpm package.
Group: Default

%description license
license components for the gpm package.


%package man
Summary: man components for the gpm package.
Group: Default

%description man
man components for the gpm package.


%package services
Summary: services components for the gpm package.
Group: Systemd services
Requires: systemd

%description services
services components for the gpm package.


%prep
%setup -q -n gpm-e82d1a653ca94aa4ed12441424da6ce780b1e530
cd %{_builddir}/gpm-e82d1a653ca94aa4ed12441424da6ce780b1e530
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689803976
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static
make  CFLAGS="$CFLAGS -Isrc/headers/"

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check

%install
export SOURCE_DATE_EPOCH=1689803976
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gpm
cp %{_builddir}/gpm-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gpm/17e3b0eea99abffe6ac71e65627413236e0b117a || :
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/gpm.service
## install_append content
ln -s libgpm.so.2  %{buildroot}/usr/lib64/libgpm.so
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../gpm.service  %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/gpm.service

%files bin
%defattr(-,root,root,-)
/usr/bin/disable-paste
/usr/bin/display-buttons
/usr/bin/display-coords
/usr/bin/get-versions
/usr/bin/gpm
/usr/bin/gpm-root
/usr/bin/hltest
/usr/bin/mev
/usr/bin/mouse-test

%files data
%defattr(-,root,root,-)
/usr/share/emacs/site-lisp/t-mouse.el
/usr/share/emacs/site-lisp/t-mouse.elc

%files dev
%defattr(-,root,root,-)
/usr/include/gpm.h
/usr/lib64/libgpm.so

%files info
%defattr(0644,root,root,0755)
/usr/share/info/gpm.info

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgpm.so.2
/usr/lib64/libgpm.so.2.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpm/17e3b0eea99abffe6ac71e65627413236e0b117a

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gpm-root.1
/usr/share/man/man1/mev.1
/usr/share/man/man1/mouse-test.1
/usr/share/man/man7/gpm-types.7
/usr/share/man/man8/gpm.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/gpm.service
/usr/lib/systemd/system/gpm.service
