#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gpm
Version  : 1fd19417b8a4dd9945347e98dfa97e4cfd798d77
Release  : 4
URL      : https://github.com/telmich/gpm/archive/1fd19417b8a4dd9945347e98dfa97e4cfd798d77.tar.gz
Source0  : https://github.com/telmich/gpm/archive/1fd19417b8a4dd9945347e98dfa97e4cfd798d77.tar.gz
Source1  : gpm.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gpm-autostart = %{version}-%{release}
Requires: gpm-bin = %{version}-%{release}
Requires: gpm-data = %{version}-%{release}
Requires: gpm-lib = %{version}-%{release}
Requires: gpm-license = %{version}-%{release}
Requires: gpm-man = %{version}-%{release}
Requires: gpm-services = %{version}-%{release}
BuildRequires : bison
BuildRequires : emacs
BuildRequires : gpm-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : texinfo
Patch1: build.patch

%description
/*
*
*
*******/
The gpm (general purpose mouse) daemon tries to be a useful mouse
server for applications running on the Linux console.  Its roots are
in the "selection" package, by Andrew Haylett, and the original code
comes from selection itself. This package is intended as a replacement
for "selection", to provide additional facilities.  From 0.18 onward
gpm supports xterm as well, so you can run mouse-sensitive
applications under X, and you can easily write curses applications
which support the mouse on both the Linux console and xterm. The xterm

%package autostart
Summary: autostart components for the gpm package.
Group: Default

%description autostart
autostart components for the gpm package.


%package bin
Summary: bin components for the gpm package.
Group: Binaries
Requires: gpm-data = %{version}-%{release}
Requires: gpm-license = %{version}-%{release}
Requires: gpm-services = %{version}-%{release}

%description bin
bin components for the gpm package.


%package data
Summary: data components for the gpm package.
Group: Data

%description data
data components for the gpm package.


%package dev
Summary: dev components for the gpm package.
Group: Development
Requires: gpm-lib = %{version}-%{release}
Requires: gpm-bin = %{version}-%{release}
Requires: gpm-data = %{version}-%{release}
Provides: gpm-devel = %{version}-%{release}
Requires: gpm = %{version}-%{release}
Requires: gpm = %{version}-%{release}

%description dev
dev components for the gpm package.


%package doc
Summary: doc components for the gpm package.
Group: Documentation
Requires: gpm-man = %{version}-%{release}

%description doc
doc components for the gpm package.


%package lib
Summary: lib components for the gpm package.
Group: Libraries
Requires: gpm-data = %{version}-%{release}
Requires: gpm-license = %{version}-%{release}

%description lib
lib components for the gpm package.


%package license
Summary: license components for the gpm package.
Group: Default

%description license
license components for the gpm package.


%package man
Summary: man components for the gpm package.
Group: Default

%description man
man components for the gpm package.


%package services
Summary: services components for the gpm package.
Group: Systemd services

%description services
services components for the gpm package.


%prep
%setup -q -n gpm-1fd19417b8a4dd9945347e98dfa97e4cfd798d77
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560260930
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make CFLAGS="$CFLAGS -Isrc/headers/"

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 check

%install
export SOURCE_DATE_EPOCH=1560260930
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gpm
cp COPYING %{buildroot}/usr/share/package-licenses/gpm/COPYING
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/gpm.service
## install_append content
ln -s libgpm.so.2  %{buildroot}/usr/lib64/libgpm.so
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../gpm.service  %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/gpm.service

%files bin
%defattr(-,root,root,-)
/usr/bin/disable-paste
/usr/bin/display-buttons
/usr/bin/display-coords
/usr/bin/get-versions
/usr/bin/gpm
/usr/bin/gpm-root
/usr/bin/hltest
/usr/bin/mev
/usr/bin/mouse-test

%files data
%defattr(-,root,root,-)
/usr/share/emacs/site-lisp/t-mouse.el
/usr/share/emacs/site-lisp/t-mouse.elc

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libgpm.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgpm.so.2
/usr/lib64/libgpm.so.2.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpm/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gpm-root.1
/usr/share/man/man1/mev.1
/usr/share/man/man1/mouse-test.1
/usr/share/man/man7/gpm-types.7
/usr/share/man/man8/gpm.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/gpm.service
/usr/lib/systemd/system/gpm.service
